apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mysqlPvName }} 
  labels:
    name: {{ .Values.mysqlPvLabel }} 
spec:
  capacity:
    storage: {{ .Values.mysqlDiskSize }} 
  accessModes: 
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.nfsServerIp }} 
    path: {{ .Values.nfsMysqlPath }} 
