apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysqlPvcName }} 
spec:
  selector:
    matchLabels:
      name: {{ .Values.mysqlPvLabel }}
  accessModes: 
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.mysqlDiskSize }} 
