apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.wordpressPvcName }} 
spec:
  selector:
    matchLabels:
      name: {{ .Values.wordpressPvLabel }} 
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.wordpressDiskSize }} 
